// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmDLqiUUvy_HvzqzNwaNIK_nTb0J02wzg',
    appId: '1:412377351142:android:7a03dbf711a2f681afcc27',
    messagingSenderId: '412377351142',
    projectId: 'pocket-puppy-rattery-c3f07',
    storageBucket: 'pocket-puppy-rattery-c3f07.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDj-aRUYJSmWUcdpNaRUMUkPTay-kVuNu0',
    appId: '1:412377351142:ios:ca7a79f52701aa88afcc27',
    messagingSenderId: '412377351142',
    projectId: 'pocket-puppy-rattery-c3f07',
    storageBucket: 'pocket-puppy-rattery-c3f07.appspot.com',
    iosClientId: '412377351142-gspvvjenerfki5tegthqlclm4nk5hp6q.apps.googleusercontent.com',
    iosBundleId: 'com.example.bugReportViewer',
  );
}
